### ISSUE TITLE
[Feature Request] Mouse over Frame, should bring it out of fade

### ISSUE THREAD

**Issue by Pheeve** [ls-/ls_Glass#10]
Is it possible to have the chat frame fade in when you move your move over the frame? I think that was the original setup as well. Right now mouse wheel down over the frame brings it up

**Comment by Pheeve** [comment]
Also removing the buttons on the left side, i thought i could remove it from blizzards stock ui....can't seem to find it now. mic/volume/etc all that nonsense. Presently i just....move it off screen :D

**Comment by ls-** [comment]
Could you show a screenshot with all the buttons in place? I just wanna see how it looks. I'll add an option to toggle them later on, although due to how the whole things works on Blizz end it's gonna be "all buttons on/off" kinda toggle.

As for the message fade in on mouseover, I had it initially, but it's resulting in so many accidental triggers that I got frustrated and removed it. I might add it as an option, but later, and it'll be off by default.

No ETAs tho.

**Comment by rml9ty** [comment]
came here to make literally this exact ticket "Mouse over Frame, should bring it out of fade". upvote for an option like this in the future.
thanks for bringing Glass back to us <3

**Comment by Aur0r4** [comment]
Hello - same here, that is the only reason I'm still using the outdated version of glass (but got Lua-Errors with it on every-lvlup, so I want to do the switch^^).

Good job btw and thank you very much for this project :)

**Comment by jscoleman22** [comment]
Please please add this option its the only thing missing from glass and its really hard to use when i have to use the scroll wheel to view the previous lines of text

**Comment by ls-** [comment]
Yes, I'll add it, I was just busy with my other addons, and I also had to deal with covid complications and then flu.

**Comment by rml9ty** [comment]
Glad to hear it's coming... Hope you feeling better soon1 <3

**Comment by ls-** [comment]
Oh, man, you can't imagine how much I want to finally feel better, being sick sucks ass 😭

**Comment by ls-** [comment]
IT. IS. DONE 🥳

![image](https://user-images.githubusercontent.com/2725970/218236842-fec4e67c-cc86-4c70-8c5e-3beb834889d0.png)

Jeez, sorry it took me so long, I'm really not doing well either physically or mentally these days 😓

**Comment by Aur0r4** [comment]
Thank you so much! <3
Much love and hugs, get well soon!
