### ISSUE TITLE
[Bug] Chat frame position resetting everytime UI is reloaded (? Blizzard issue)

### ISSUE THREAD

**Issue by JBabbb** [ls-/ls_Glass#12]
Chat is resetting to default size everytime I reload the UI. Started happening 30 minutes ago from report.

Not sure why it is happening, or if anyone else is having this issue!

EDIT: upon further investigation, I think this could be a Blizzard issue, the quest log has also been moving vertically during the same period the chat has gone wonky.

**Comment by migwynkriid** [comment]
LS (Developer) did manage to fix a similiar kind of issue on my end, the fix was to uncheck "Raid Frames" in Blizzards Edit Mode. Try that and report back.

**Comment by ls-** [comment]
Don't get me started on all the "Edit Mode" bugs. Sometimes you need to save things twice. Like, you move a frame, you hit save, then you move it again, and hit save again. And only then it'll actually save its position properly. It's not unique to the chat frame.

**Comment by JBabbb** [comment]
Just getting on now, will give what you said a go! :D

**Comment by ls-** [comment]
You'll have to be patient with Blizz layout manager for the time being, prob until 10.1 even.... It's not raw, but it's def half-cooked 😅

**Comment by JBabbb** [comment]
No stress, if I have to configure the chat everytime I hop on for now it's ok. Not ur fault :)

It's so much better than default chat, so thank you so much for doing this!

**Comment by ls-** [comment]
> No stress, if I have to configure the chat everytime I hop on for now it's ok.

This really shouldn't be happening. Something is really wrong here, in the worst case scenario, just disable **all** addons, position chat and other frames, reenable addons.
