### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Geekfoxxx** [ls-/ls_Glass#15]
Hi, since I am using a 4k Monitor and want the chat to be really small can you add more fonz sizes (maybe down to 6)?

**Comment by ls-** [comment]
Damn, 6 is smol like an 🐜. I'll add it, no biggie.

But you'll have to wait, I'll return to working on glass in a week or so because I currently work on my other projects.

**Comment by Geekfoxxx** [comment]
Thanks for your answer. 

 

Will look into your other projects aswell.

 

Greetings from germany!

 

Gesendet: Dienstag, 15. November 2022 um 03:37 Uhr
Von: "Val Voronov" ***@***.***>
An: "ls-/ls_Glass" ***@***.***>
Cc: "Geekfoxxx" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [ls-/ls_Glass] Font Size (Issue #15)


 

Damn, 6 is smol like an 🐜. I'll add it, no biggie.

But you'll have to wait, I'll return to working on glass in a week or so because I currently work on my other projects.
