### ISSUE TITLE
Longer fade out delay

### ISSUE THREAD

**Issue by Grenmund** [ls-/ls_Glass#16]
Please allow us to increase the time before fadeout, even at maximum it feels like it fades too quickly and can fade out mid-conversation.

**Comment by ls-** [comment]
Mmmm, 20s is a lot actually, I'll bump it up to 30s, however, there's a "hidden" feature 😉 When you have your cursor is over the chat frame the addon stops messages from fading out, that's basically how you tell it that you're actively chatting.

That said, I prob should add some checks to the edit box, so the fading timer resets whenever it gains focus, basically, whenever you it's possible for you to type in it.

As I said in another issue, the addon is currently stable, so I'm working on my other stuff, unless some addon/game-breaking stuff occurs I won't start working on glass until after a week or so 😅

**Comment by ls-** [comment]
Oh, nyo! Don't close it! I need it as a reminder 🤣

**Comment by beijer** [comment]
Is there any reason to limit it at all, let the users decide?
Love the addon, this is the only thing that annoys me.

**Comment by ls-** [comment]
Normally, it's done due to prevent stuff from just hanging in the system for too long while doing nothing. I honestly, can't even begin to image why anyone would need such a long fade out delay 😅

**Comment by beijer** [comment]
I really depends on where you are, 20/30s only works if you are watching chat constantly. But as I said, there is no reason to deside for the users how long time they want the messages to be visible. Maybe they are only looking for the animation for new messages and therefor want a longer time. I change the source by myself to 60s and that felt way better for me.

**Comment by SkywardShadow** [comment]
Ah, I see why there may be some confusion. I never see a lot of messages in a short time. General, trade, etc. are in a separate tab that I don't have up by default. Whereas I have a chat window up that only shows current instance chat, emotes, etc. 

So when, for example, tanking a dungeon I am not often looking at that chat in combat, but once combat is over I glance at the window to see what is being said, and am not used to a quick fade removing any instance chat.

**Comment by ls-** [comment]
It'll be bumped to 120s in the next update, I hope that will be enough. But I'm also working on an option to fade-in messages on mouse over, so these two combined should address all the concerns 😓
