### ISSUE TITLE
Unable to move cursor via arrow keys

### ISSUE THREAD

**Issue by hrothmar** [ls-/ls_Glass#17]
**Issue:**
When typing into LS-Glass chat window, I cannot move the cursor via the Left/Right arrow key while typing into the chat. 

**How to replicate:**

1. Press enter to begin typing a new message into LS-Glass. 
2. Type a short message into the chat (even just a few character long)
3. Press the left arrow button to try and navigate to an earlier point in the message string that you typed

Visual example:
![image](https://user-images.githubusercontent.com/110924661/201761957-227a9f69-64e1-4eb3-8f19-4618cdfafacf.png)

**Current behavior:**
The cursor does not move earlier into the message, and the character turns left.

**Expected behavior:**
The cursor moves one letter earlier in the message's typing field, with long presses doing multiple moves.

**Other Notes:**
At this time, it appears that Left Arrow is being pressed as a global button (ie: there's detection that the focus is inside of the Chat Box, instead it attempts to run whatever is associated with the left arrow key (turn character by default).

**Comment by hrothmar** [comment]
As a bonus

**Comment by ls-** [comment]
Yeah, in the default UI you need to use alt+arrow keys. Consider checking out `BasicChatMods`, it's lightweight and has some features my addon currently misses or I have no plans to add. 

Dw, stuff like that happens 😁

**Comment by hrothmar** [comment]
definitely just too used to ElvUI which had it baked in, thanks for the rec!

**Comment by ls-** [comment]
> People say I have a nice voice.

You do :>

**Comment by hrothmar** [comment]
thank you so much! 🥰
