### ISSUE TITLE
[Feature Request] Option to hide or fade Social Button 

### ISSUE THREAD

**Issue by RevolutionNin3** [ls-/ls_Glass#18]
Would it be possible to add an option to hide the social button or add it to the chat window's fade?

**Comment by ls-** [comment]
It's planned, yes, I'm just not exactly sure what I wanna do with that button atm 😅

For the time being consider using something like `BasicChatMods`, it's lightweight and pretty compatible with my addon. It has features my addon currently lacks, but there's also some overlap, like editbox settings and whatnot, disable them in that addon :>

**Comment by ls-** [comment]
Almost 2 years later, but it's finally happening!

![glass_button_fading](https://github.com/ls-/ls_Glass/assets/2725970/38eda854-f020-4dc3-ac3f-c3d20213e3bd)

[Better late than never](https://github.com/ls-/ls_Glass/commit/6ad1882630e22b3a04d77abaffae333d3b652981), I guess...
