### ISSUE TITLE
[Feature Request] Multiple chat windows

### ISSUE THREAD

**Issue by Lunaeria** [ls-/ls_Glass#2]
Hello! The original Glass addon didn't have this feature, which made me terribly sad because it would otherwise be the perfect chat addon for me!

I like to have two chat windows onscreen; one for all the actual chatting and its respective tabs, and the other for loot/system messages/etc. so that those things don't clutter up my chat, whilst still always being visible as they occur.

With that in mind, do you think it'd be possible to integrate multiple chat windows into Glass? Same functionality and all on both!

If it's not possible, I understand completely, and if it's already a feature, I apologise for being a doofus and not noticing!

Thank you for your hard work, it's extremely appreciated!!

**Comment by ls-** [comment]
Since it's already an option in the default UI my addon supports it without interfering with it in any way.

![image](https://user-images.githubusercontent.com/2725970/200959074-9d49675a-5246-41f6-8164-3af3882777f4.png)

<3

**Comment by Lunaeria** [comment]
Wahoo! Amazing!! You're an absolute star. I recall it not working too well or at all with the original addon, so I am very grateful for whatever tinkering you've done for this feature, intended or not!

Thank you so very much, and I hope you have the loveliest of days!
