### ISSUE TITLE
[Feature Request] Compatiable With Another Addon

### ISSUE THREAD

**Issue by Yamr3** [ls-/ls_Glass#20]
Any chance you can make the animated Twitch emotes work as well? The static ones work but the animated ones only move by 1 frame when you scroll up or down.

[Twitch Emotes v2](https://www.curseforge.com/wow/addons/twitch-emotes-v2)

**Comment by ls-** [comment]
I'll look into how it works later, so I can't guarantee anything atm. Rn I'm busy with my other addons >_>

**Comment by ls-** [comment]
I'm not sure when I fixed that, but it's been working for quite a while :D

![image](https://github.com/ls-/ls_Glass/assets/2725970/20b07019-6344-4fc8-bb98-45d2431e6e01)
