### ISSUE TITLE
[Bug] Mouseover profession links automatically opens the hovered profession window

### ISSUE THREAD

**Issue by tmgsca** [ls-/ls_Glass#23]
Noticed this as I started to see more posts on trade chat with profession links. When you mouse over a profession link, it seems a click is triggered automatically. This happens often when trying to scroll the chat with the mouse wheel.

**Comment by truckcarr11** [comment]
You might already be aware, but it seems this is caused buy the setting "Mouseover Tooltips". Assuming the way it displays the tooltip uses the click functionality which is causing it to open the large profession window when the profession links are hovered.

**Comment by truckcarr11** [comment]
I created a PR to fix this.
#24

**Comment by ls-** [comment]
Merged, but I'll release an update later, I'll deal with few other things first <3
