### ISSUE TITLE
[Feature Request] Flip Chat Text

### ISSUE THREAD

**Issue by Quearrel** [ls-/ls_Glass#25]
If it is possible, make it so that there is the option in settings to flip the chat window, So that new messages arrive from the top of the window, and the old ones are at the bottom/phase out mid/bottom. This would help me a lot with how my in-game UI is, and i feel it would be a great addition to the customization for others who have their chat like mine, or would just prefer it this way for any reason.

I also think it would be interesting to see if it could be done for the sides, as well.

**Comment by ls-** [comment]
At this point this is definitely not happening. I'm currently rewriting the addon to allow for smooth scrolling through the message history, so stuff like that will overcomplicate things for me.

![smooth-scrolling-test](https://github.com/ls-/ls_Glass/assets/2725970/d0d80a33-f923-47fa-95b2-b8671b97390c)
The green stuff is just there for debugging.
