### ISSUE TITLE
[Feature Request] Move edit box

### ISSUE THREAD

**Issue by tmgsca** [ls-/ls_Glass#3]
First of all, thank you so much for picking up this addon.

One feature of the original Glass addon, was the ability to move the edit box. This made it possible, for instance, to attach the chat to the bottom left corner of the screen, and still have the edit box within bounds.

Would love if you could consider adding this capability to LS: Glass 😄 

![WoWScrnShot_110922_214756](https://user-images.githubusercontent.com/5647031/200988778-d5eb315c-15fb-4012-8e6e-e3dece6ce458.jpg)

**Comment by ls-** [comment]
Hi! Yeah, I'm planning to add it, this seems to be a weirdly commonly requested feature, haha 😅

**Comment by ls-** [comment]
Done! I'll release it with `.05`.

**Comment by tmgsca** [comment]
@ls- thanks for implementing this. There is one "issue" however, related to how I prefer to use it. I like to position the chat all the way to the bottom of the screen, but if I do that using Edit Mode, the edit box will be off-screen, since there is no way to apply a negative offset to it.

Do you think you could either allow negative values on the offset, or change the way the chat box frame is calculated, so that its size is measured by the chat panel only instead of also accounting for the edit box?

**Comment by ls-** [comment]
Hmm, so do you basically have your editbox set up like this? 

![edit_box_pv](https://user-images.githubusercontent.com/2725970/201810369-b860f265-4078-407b-aa1f-0ec4cf897e4a.gif)

I'll add it, no problem, but atm I'm working on my other addons. I rotate between addons unless some addon/game-breaking stuff occurs. This addon is pretty stable now, `.05` addressed the worst issues, so I'll come back to it in a week or so 😊😅

**Comment by tmgsca** [comment]
> Hmm, so do you basically have your editbox set up like this?
> 
> ![edit_box_pv](https://user-images.githubusercontent.com/2725970/201810369-b860f265-4078-407b-aa1f-0ec4cf897e4a.gif) [ ![edit_box_pv](https://user-images.githubusercontent.com/2725970/201810369-b860f265-4078-407b-aa1f-0ec4cf897e4a.gif) ](https://user-images.githubusercontent.com/2725970/201810369-b860f265-4078-407b-aa1f-0ec4cf897e4a.gif) [ ](https://user-images.githubusercontent.com/2725970/201810369-b860f265-4078-407b-aa1f-0ec4cf897e4a.gif)
> 
> I'll add it, no problem, but atm I'm working on my other addons. I rotate between addons unless some addon/game-breaking stuff occurs. This addon is pretty stable now, `.05` addressed the worst issues, so I'll come back to it in a week or so 😊😅

Exactly, sorry if my first screenshot wasn't clear enough. Thank you again, great work!

**Comment by OttoDeFe** [comment]
With the edit box at the top I can't access the tabs...

**Comment by ls-** [comment]
I'm finally back and I'm slowly working on the issues 🥳
