### ISSUE TITLE
Error when using "open whispers in a new tab" in blizzard's social settings

### ISSUE THREAD

**Issue by ShadowSingularity** [ls-/ls_Glass#30]
When i get a whisper i get this error in bugsack, it also pops when i whisper someone or when i reply in a whisper tab, it also doesnt scroll or show the new lines that i typed in that same whisper tab unless i scroll down.

1x ls_Glass/core/components/button.lua:69: attempt to index a nil value
[string "@ls_Glass/core/components/button.lua"]:69: in function `HandleMinimizeButton'
[string "@ls_Glass/init.lua"]:636: in function <ls_Glass/init.lua:629>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `FCF_OpenTemporaryWindow'
[string "@FrameXML/FloatingChatFrame.lua"]:2589: in function <FrameXML/FloatingChatFrame.lua:2572>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 CreateFonts = <function> defined @ls_Glass/core/components/fonts.lua:10
 UpdateMessageFont = <function> defined @ls_Glass/core/components/fonts.lua:68
 EnableModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 ShowLinkCopyPopup = <function> defined @ls_Glass/core/core.lua:323
 baseName = "ls_Glass"
 IterateEmbeds = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 Modernize = <function> defined @ls_Glass/core/modernize.lua:9
 CHANGELOG = "## Version 100100.01

- Added 10.1.0 support.
"
 ProcessText = <function> defined @ls_Glass/core/core.lua:34
 SetDefaultModulePrototype = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 ResetSlidingFrameDockFading = <function> defined @ls_Glass/core/components/slidingmessageframe.lua:696
 defaultModuleState = true
 IsEnabled = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 FadeIn = <function> defined @ls_Glass/core/core.lua:187
 DisableModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 FadeOut = <function> defined @ls_Glass/core/core.lua:193
 RegisterMessage = <function> defined @LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 UpdateBackdrops = <function> defined @ls_Glass/core/components/backdrop.lua:40
 HandleEditBox = <function> defined @ls_Glass/core/components/editbox.lua:21
 UpdateMessageLinesBackgrounds = <function> defined @ls_Glass/core/components/messageline.lua:73
 SetEnabledState = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 StopFading = <function> defined @ls_Glass/core/core.lua:199
 RegisterEvent = <function> defined @LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 CreateColor = <function> defined @ls_Glass/core/core.lua:249
 UpdateMessageLinesHeights = <function> defined @ls_Glass/core/components/messageline.lua:85
 IterateModules = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 UpdateEditBoxes = <function> defined @ls_Glass/core/components/editbox.lua:49
 HandleMenuButton = <function> defined @ls_Glass/core/components/button.lua:93
 HandleOverflowButton = <function> defined @ls_Glass/core/components/button.lua:100
 Enable = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 SetSlidingFrameForChatFrame = <function> defined @ls_Glass/core/components/slidingmessageframe.lua:24
 GetName = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "ls_Glass"
 Subscribe = <function> defined @ls_Glass/core/core.lua:53
 orderedModules = <table> {
 }
 HandleMinimizeButton = <function> defined @ls_Glass/core/components/button.lua:65
 Disable = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 CreateMessageLinePool = <function> defined @ls_Glass/core/components/messageline.lua:59
 VER = <table> {
 }
 OnEnable = <function> defined @ls_Glass/init.lua:569
 OnInitialize = <function> defined @ls_Glass/init.lua:27
 modules = <table> {
 }
 HandleChatTab = <function

**Comment by ls-** [comment]
That's strange, I get whispers all the time and I don't experience anything like that. I saw a similar report all the way back in March, but I couldn't reproduce it. Are you on retail or some flavour of classic?

**Comment by ShadowSingularity** [comment]
Retail.

**Comment by ls-** [comment]
That is super weird... 🤔 What's your client's language? I wonder if it's locale specific...

**Comment by ShadowSingularity** [comment]
English, ill play around with the whispers some more when i am ingame again, maybe ill get a different error :)

**Comment by ls-** [comment]
Are you in my discord? It'll be a lot easier and faster to ask question and other stuff there 😅
Tbqh, what I need from you right now is the screenshot of your "Social" settings.

![image](https://github.com/ls-/ls_Glass/assets/2725970/98c637e9-ae86-4cfd-ae2c-b84b7fe3c17c)

I might be able to find a hint there. But so far, I have no idea, whispers work perfectly fine for me. Like, I'd notice if something as basic as that was broken, but as I said, I had it reported once all the way back in March 🤔 Ugh...

**Comment by ls-** [comment]
Btw? Do you use any addons that do something to chat in terms of visuals? The person that reported this bug used either ElvUI or TukUI. I wonder if the frame I'm referencing in my code isn't accessible/reachable via normal means because of that 🤔

**Comment by ShadowSingularity** [comment]
Ill join in a bit, uninstalled elvui a long time ago, ill get you that screenshot as soon as i can! 👍
