### ISSUE TITLE
Feature Request Classic Support

### ISSUE THREAD

**Issue by AngelosNaoumis** [ls-/ls_Glass#31]
Any chance to support classic?

**Comment by goldenpipes** [comment]
[there is this version](https://www.curseforge.com/wow/addons/glass-wotlk-classicera)

it works well, but it doesn't support multiple windows, it supports multiple tabs though, i have ZERO experience with LUA, but im going to look at the code and see what i can see.

**Comment by Master0fEvil** [comment]
> [there is this version](https://www.curseforge.com/wow/addons/glass-wotlk-classicera)
> 
> it works well, but it doesn't support multiple windows, it supports multiple tabs though, i have ZERO experience with LUA, but im going to look at the code and see what i can see.

another problem with it is no tab alerts

**Comment by ls-** [comment]
Classic support is definitely not happening because I'm only playing retail. Ngl, supporting even one WoW flavour is a pain these days due to my real life issues.
