### ISSUE TITLE
"Enter message" box

### ISSUE THREAD

**Issue by EliseyMartynov** [ls-/ls_Glass#32]
Hi! Thank you for the addon and the effort you're putting into this.
Could you tell me please, is there a way to hide a placeholder "Type /5... etc." in enter window box. Or a way to fade it?

![image](https://github.com/ls-/ls_Glass/assets/66368523/1271dd38-2c0e-4e56-86de-8d75ef4d188b)

**Comment by ls-** [comment]
It's something Blizz do, while possible I try not to mess with that kind of things aimed at newbies specifically.
