### ISSUE TITLE
[Feature Request] Fade out the Input-Field and Social-Button

### ISSUE THREAD

**Issue by Tr4p** [ls-/ls_Glass#33]
I love the fact, that the chat fades out. It makes the view clear and enyojable
But after the chat fades out there is still the Input-Field and Social-Button left over.
It would be great if these also would fade out.

**Comment by ls-** [comment]
Social button fading is coming in TWW

![glass_button_fading](https://github.com/ls-/ls_Glass/assets/2725970/38eda854-f020-4dc3-ac3f-c3d20213e3bd)

As for the "input-field", you're using the "IM" chat style, it's a Blizz "Social" setting.

![image](https://github.com/ls-/ls_Glass/assets/2725970/92015670-f9a0-4e98-8f26-89b81193e401)

That edit box properly fades out when you use the "Classic" style.
