### ISSUE TITLE
[Font bug] Limited support for Cyrillics

### ISSUE THREAD

**Issue by Sluimerstand** [ls-/ls_Glass#36]
When using the Fritz Quadrata font, the same one the game should be using, as soon as Cyrillic characters show up in chat, the font changes and even stops using an outline as set by my settings.

![image](https://github.com/ls-/ls_Glass/assets/29845810/4bca230c-f267-493b-8c10-26171472ba10)

**Comment by ls-** [comment]
Sadly, there's just nothing I can do about it due to how fonts are implemented, we simply don't have enough control over this stuff from Lua 😭
