### ISSUE TITLE
[Bug] Custom font need to be re-applied on every login/reload

### ISSUE THREAD

**Issue by Xzsyn** [ls-/ls_Glass#4]
As the title says, I need to re-apply the custom font everytime I login or reload my UI. I do have an addon changing Blizzard master fonts, however, not sure if that might interfere? But I did check without that addon, and the problem persisted.

Anyway, thank you for your work, this addon is amazing.

**Comment by ls-** [comment]
Yeah, heard this report earlier as well, it happens when you use custom fonts from an addon that loads later. 369fa14973ec0b69f91cdbd7c56b34a94019d9b2 fixes that.
