### ISSUE TITLE
Duplicate messages with multiple chat windows in 110000.01

### ISSUE THREAD

**Issue by glassleo** [ls-/ls_Glass#40]
Hey!

I keep getting duplicate messages in all my chat windows for some message types. It seems to be happening with say messages, emotes and creature messages. I double checked which message types each window has and they shouldn't appear in more than one. With the addon disabled I don't get duplicates.

**Comment by ls-** [comment]
Blizz for some reason partially reset chat options, "Say" got enabled in all chat windows. I ran into this issue too, I had a bunch of things re-enabled in my combat log of all things.

![image](https://github.com/user-attachments/assets/4f3d0239-4cef-441a-a406-63d75f46c899)

I purposefully chose not to mess with those settings from inside the addon, so you'll have to disable it again in Blizz chat config.

![image](https://github.com/user-attachments/assets/44479735-aafb-4f53-9ec5-27e424ad6512)

Hopefully, it's a one time thing, but if it happens again, you know where to find it.

**Comment by glassleo** [comment]
Seems to be happening randomly on login that all chat settings get borked.

Has nothing to do with Glass though, I just assumed so after my limited testing.
