### ISSUE TITLE
Error when doing pet battles

### ISSUE THREAD

**Issue by tommy610** [ls-/ls_Glass#5]
This error shows up when I start a pet battle.

2x Interface/AddOns/ls_Glass/init.lua:568: table index is nil
[string "@Interface/AddOns/ls_Glass/init.lua"]:568: in function <Interface/AddOns/ls_Glass/init.lua:563>
[string "=[C]"]: in function `FCF_SetTemporaryWindowType'
[string "@Interface/FrameXML/FloatingChatFrame.lua"]:831: in function <Interface/FrameXML/FloatingChatFrame.lua:787>
[string "=[C]"]: in function `FCF_OpenTemporaryWindow'
[string "@Interface/AddOns/Blizzard_PetBattleUI/Blizzard_PetBattleUI.lua"]:173: in function `PetBattleFrame_Display'
[string "@Interface/AddOns/Blizzard_PetBattleUI/Blizzard_PetBattleUI.lua"]:109: in function <...AddOns/Blizzard_PetBattleUI/Blizzard_PetBattleUI.lua:106>

Locals:
chatFrame = ChatFrame11 {
 SetJustifyV = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 isLayoutDirty = true
 isDisplayDirty = true
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 BaseAddMessage = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 SetFont = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetIndentedWordWrap = <function> defined =[C]:-1
 buttonSide = "left"
 GetFont = <function> defined =[C]:-1
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 PageUp = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 textIsCopyable = false
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 overrideFadeTimestamp = 0
 MarkDisplayDirty = <function> defined =[C]:-1
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 CanEffectivelyFade = <function> defined =[C]:-1
 OnPreSizeChanged = <function> defined =[C]:-1
 OnPostMouseUp = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 name = "Pet Battle Combat"
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessage = <function> defined @Interface/FrameXML/ChatFrame.lua:2786
 InitializeFontableFrame = <function> defined =[C]:-1
 GetShadowColor = <function> defined =[C]:-1
 isUninteractable = false
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 originalShow = <function> defined =[C]:-1
 AcquireFontString = <function> defined =[C]:-1
 TransformMessages = <function> defined =[C]:-1
 AtBottom = <function> defined =[C]:-1
 buttonFrame = ChatFrame11ButtonFrame {
 }
 HasFontObject = <function> defined =[C]:-1
 GetOnTextCopiedCallback = <function> defined =[C]:-1
 SetFading = <function> defined =[C]:-1
 OnPostHide = <function> defined =[C]:-1
 ScrollByAmount = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 hasOwnFontObject = true
 Clear = <function> defined =[C]:-1
 oldAlpha = 0
 channelList = <table> {
 }
 GetTimeVisible = <function> defined =[C]:-1
 IsSelectingText = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 Show = <function> defined @Interface/FrameXML/FrameLocks.lua:141
 BackFillMessage = <function> defined =[C]:-1
 isTemporary = true
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = Frame {
 }
 SetShadowOffset = <function> defined =[C]:-1
 messageTypeList = <table> {
 }
 timeVisibleSecs = 120
 PackageEntry = <function> defined =[C]:-1
 MakeFontObjectCustom = <function> defined =[C]:-1
 fontObject = table: 000002CFF4B6FE00 {
 }
 SetInsertMode = <function> defined =[C]:-1
 isRegistered = true
 originalHide = <function> defined =[C]:-1
 ScrollDown = <function> defined =[C]:-1
 zoneChannelList = <table> {
 }
 SetScrollOffset = <function> defined =[C]:-1
 onDisplayRefreshedCallback = <function> defined =[C]:-1
 insertMode = 2
 ResetSelectingText = <function> defined =[C]:-1
 chatType = "PET_BATTLE_COMBAT_LOG"
 Hide = <function> defined @Interface/FrameXML/FrameLocks.lua:137
 GetTextColor = <function> defined =[C]:-1
 inUse = true
 ResetAllFadeTimes = <function> defined =[C]:-1
 GatherSelectedText = <function> defined =[C]:-1
 SetShadowColor = <function> defined =[C]:-1
 0 = <userdata>
 GetNumVisibleLines = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 ResizeButton = ChatFrame11ResizeButton {
 }
 fadeDurationSecs = 3
 ScrollToBottom = <function> defined =[C]:-1
 ScrollToTop = <function> defined =[C]:-1
 onScrollChangedCa

**Comment by ls-** [comment]
Hi! It's already fixed in f3e3b780ae41976f28d613accbd467d2e2796c56, I just haven't released an update yet.
