### ISSUE TITLE
[Feature Request] Text alignment (Left/Centre/Right)

### ISSUE THREAD

**Issue by Lunaeria** [ls-/ls_Glass#7]
*tiptoes in* Hi, it's me... back again!

Following on from my previous request about separate windows, I've now gotten a chance to install and try out the addon in-game and you were right! The additional windows work perfectly! Wahoo!

However, I was wondering if it would be possible to add text alignment as an option?

And, crucially, would it also be possible to make it so that you can set separate chat windows to different alignments? 

Again, I do understand completely if it's too much trouble, so please don't worry if it's not possible to implement. 

Thank you so much all the same!

**Comment by ls-** [comment]
I am considering add enlightenment options, however, I **REALLY** don't want to have separate chat options for different chat windows, it add a pretty annoying level of complexity I just straight up don't want to deal with atm.

**Comment by ls-** [comment]
I toyed with this idea during my rewrite, and it simply doesn't work, it looks weird, to put it mildly.

![image](https://github.com/ls-/ls_Glass/assets/2725970/cebc36f9-3966-460b-a312-2ee755b3ad78)
