### ISSUE TITLE
[Feature Request] Scroll bar/buttons

### ISSUE THREAD

**Issue by Lunaeria** [ls-/ls_Glass#8]
This one, I understand, will be _very_ niche, but... I don't have a scroll wheel on my mouse!

Do you think it'd be possible to make the default scrollbar toggleable in the options? (Appearing only on mouseover, of course!)

It would help tremendously with accessibility, and I promise that with this and my other request (text alignment), I will _almost definitely_ stop poking you for new features!!

Thank you again! :D

**Comment by ls-** [comment]
![](https://media.tenor.com/9AxpRD2d5d0AAAAd/blinking-eyes-man.gif)

**Comment by ls-** [comment]
For the love of holy cow, include details like that whenever you make feature request. Specific usecases when described help a lot to understand the cause of the issue. This request went from "wtf? 🤨" to "hmmm, makes sense, I'll think about... 🤔"

**Comment by Lunaeria** [comment]
Ah, sorry! I noted that it was because I lacked a scroll wheel, but I wasn't sure if it would be necessary to detail exactly why. Like I said, I'm probably the only user of the addon that has this issue, so if it's not an easy addition, please don't worry about it!

**Comment by ls-** [comment]
Nah, this request + #6 made me consider adding toggles for re-enabling some default chat elements. I'll prob reskin them so that they don't look out of place, but it's now something I may add later.

**Comment by ls-** [comment]
Finally got around to working on glass. With the next update I'll add optional scroll up and down buttons above the scroll to bottom button.

![image](https://user-images.githubusercontent.com/2725970/218233647-beceb058-30e0-4982-a6fd-0a0157828191.png)

![image](https://user-images.githubusercontent.com/2725970/218233636-e87bd5e5-1a7c-44e4-bbde-d3f4f4e4e6f7.png)
